### ISSUE TITLE
stylelint-require-units incompatibility (false positives)

### ISSUE THREAD

**Issue by rdgomt** [hudochenkov/postcss-styled-syntax#5]
Hi! I am trying to migrate from postcss-styled-components, but I am facing an issue with a stylelint plugin called matterialize/stylelint-require-units. Here are the false positives that are showing:

<img width="1080" alt="Captura de Tela 2023-01-30 às 17 30 04" src="https://user-images.githubusercontent.com/23437436/215588680-6c77ae5a-ba11-404e-a031-475217d8d2d0.png">

<img width="1084" alt="Captura de Tela 2023-01-30 às 17 30 13" src="https://user-images.githubusercontent.com/23437436/215588700-8725b514-a467-458e-a37d-963aba892035.png">

**Comment by hudochenkov** [comment]
Hey! Great to hear about more adoption :)

It should be fixed in the rule. This package produces AST (Abstract Syntax Tree) where property value is everything that comes after `:`. So in your case is is `${props => showBottomBorder ? 1 : 0}px`. Many rules would not be prepared for such values.

In Stylelint we use [isStandardSyntaxValue](https://github.com/stylelint/stylelint/blob/main/lib/utils/isStandardSyntaxValue.js) helper function in rules to ignore properties which have non-standard values like in your example. Then in rule we [return early](https://github.com/stylelint/stylelint/blob/f8988a10455be84b27c300631c902e289cfc730c/lib/rules/color-named/index.js#L76-L78) for non-standard syntax before rule make any checks. This approach ignores properties, which rule can't understand and produces no violations.

Please, open an issue in `matterialize/stylelint-require-units` repository, so they could adopt what Stylelint does.

**Comment by rdgomt** [comment]
Thank you for the explanation.
